CREATE TABLE IF NOT EXISTS users (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    isAdmin INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS roasting (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    roaster TEXT NOT NULL,
    comment TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);